import React, { Fragment } from 'react';

// Nextjs
import Head from 'next/head';
import NextLink from 'next/link';
import Image from 'next/image';

// MUI
import { Box, Card, Container, Divider, Link, Typography } from '@mui/material';

// GuestGuard
import { GuestGuard } from '../components/authentication/guest-guard';

// Login Component
import JWTLogin from '../components/authentication/jwt-login';

// Logo from Public Dir
import DVHotelLogo from '../../public/Logo/HLogo.png';

const Home = () => {
  return (
    <Fragment>
      <Head>
        <title>DV Hotel</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/Logo/HLogo.png' />
      </Head>

      <Box
        component={'main'}
        sx={{
          backgroundColor: 'background.default',
          display: 'grid',
          placeItems: 'center',
          minHeight: '100vh',
        }}>
        <Container
          maxWidth='sm'
          sx={{
            py: {
              xs: '60px',
              md: '60px',
            },
          }}>
          <Card elevation={16} sx={{ p: 4 }}>
            <Box
              sx={{
                alignItems: 'center',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
              }}>
              <NextLink href='/' passHref>
                <a>
                  <Image src={DVHotelLogo} alt='DV Hotel' objectFit={'cover'} />
                </a>
              </NextLink>
              <Typography variant='h4'>Log in</Typography>
            </Box>
            <Box
              sx={{
                flexGrow: 1,
                mt: 3,
              }}>
              <JWTLogin />
            </Box>
            <Divider sx={{ my: 3 }} />
            <Box
              component={'div'}
              sx={{
                display: 'flex',
                justifyContent: 'flex-end',
              }}>
              <NextLink href={'/authentication/password-recovery'} passHref>
                <Link color='textSecondary' sx={{ mt: 1 }} variant='body2'>
                  Forgot password
                </Link>
              </NextLink>
            </Box>
          </Card>
        </Container>
      </Box>
    </Fragment>
  );
};

Home.getLayout = (page) => <GuestGuard>{page}</GuestGuard>;

export default Home;
